### ISSUE TITLE
Pending List

### ISSUE THREAD

**Issue by kristenmills** [Flexget/webui#3]
TODO:
- [x] Add List (#30)
- [x] View Lists (#30)
- [x] Add Entry (#30)
- [x] View List Entries (#30)
- [x] Approve/Reject Entry (#30)
- [x] Remove/Inject Entry (#30)
- [x] hooks version (#44)
- [x] Fix FlexgetEntry (#44)
- [x] New Pagination and Sort (#44)
- [x] Remove List UI (#44)
- [x] Add Entry UI (#44)
- [x] Support Injectable AppBar (#53)
- [ ] Tests  (#54)
- [ ] Bulk add and removal (#54)
