### ISSUE TITLE
Series FF

### ISSUE THREAD

**Issue by kristenmills** [Flexget/webui#67]
- [x] Cleanup series skeleton (#68)
- [ ] add begin and latest series ( #70)
- [x] back button header (#68)
- [x] Delete/Reset all releases (#69)
